// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MTransfCtrl.proto

package dms;

public final class MTransfCtrlOuterClass {
  private MTransfCtrlOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MTransfCtrlOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dms.MTransfCtrl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
     * </pre>
     *
     * <code>optional int32 Msgtype = 1;</code>
     */
    boolean hasMsgtype();
    /**
     * <pre>
     *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
     * </pre>
     *
     * <code>optional int32 Msgtype = 1;</code>
     */
    int getMsgtype();

    /**
     * <pre>
     *系统类型
     * </pre>
     *
     * <code>optional uint32 SysType = 2;</code>
     */
    boolean hasSysType();
    /**
     * <pre>
     *系统类型
     * </pre>
     *
     * <code>optional uint32 SysType = 2;</code>
     */
    int getSysType();

    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     */
    boolean hasFromAppID();
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     */
    java.lang.String getFromAppID();
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     */
    com.google.protobuf.ByteString
        getFromAppIDBytes();

    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     */
    boolean hasMsgName();
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     */
    java.lang.String getMsgName();
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     */
    com.google.protobuf.ByteString
        getMsgNameBytes();

    /**
     * <pre>
     *传递的消息
     * </pre>
     *
     * <code>optional bytes data = 6;</code>
     */
    boolean hasData();
    /**
     * <pre>
     *传递的消息
     * </pre>
     *
     * <code>optional bytes data = 6;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code dms.MTransfCtrl}
   */
  public  static final class MTransfCtrl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dms.MTransfCtrl)
      MTransfCtrlOrBuilder {
    // Use MTransfCtrl.newBuilder() to construct.
    private MTransfCtrl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MTransfCtrl() {
      msgtype_ = 0;
      sysType_ = 0;
      timestamp_ = "";
      fromAppID_ = "";
      msgName_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MTransfCtrl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgtype_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sysType_ = input.readUInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              timestamp_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              fromAppID_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              msgName_ = bs;
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dms.MTransfCtrlOuterClass.MTransfCtrl.class, dms.MTransfCtrlOuterClass.MTransfCtrl.Builder.class);
    }

    private int bitField0_;
    public static final int MSGTYPE_FIELD_NUMBER = 1;
    private int msgtype_;
    /**
     * <pre>
     *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
     * </pre>
     *
     * <code>optional int32 Msgtype = 1;</code>
     */
    public boolean hasMsgtype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
     * </pre>
     *
     * <code>optional int32 Msgtype = 1;</code>
     */
    public int getMsgtype() {
      return msgtype_;
    }

    public static final int SYSTYPE_FIELD_NUMBER = 2;
    private int sysType_;
    /**
     * <pre>
     *系统类型
     * </pre>
     *
     * <code>optional uint32 SysType = 2;</code>
     */
    public boolean hasSysType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *系统类型
     * </pre>
     *
     * <code>optional uint32 SysType = 2;</code>
     */
    public int getSysType() {
      return sysType_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private volatile java.lang.Object timestamp_;
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *时间戳
     * </pre>
     *
     * <code>optional string Timestamp = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMAPPID_FIELD_NUMBER = 4;
    private volatile java.lang.Object fromAppID_;
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     */
    public boolean hasFromAppID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     */
    public java.lang.String getFromAppID() {
      java.lang.Object ref = fromAppID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fromAppID_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *消息来源ID
     * </pre>
     *
     * <code>optional string FromAppID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFromAppIDBytes() {
      java.lang.Object ref = fromAppID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromAppID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object msgName_;
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     */
    public boolean hasMsgName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     */
    public java.lang.String getMsgName() {
      java.lang.Object ref = msgName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgName_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *传递的消息名称
     * </pre>
     *
     * <code>optional string MsgName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMsgNameBytes() {
      java.lang.Object ref = msgName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     *传递的消息
     * </pre>
     *
     * <code>optional bytes data = 6;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *传递的消息
     * </pre>
     *
     * <code>optional bytes data = 6;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, msgtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, sysType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fromAppID_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, msgName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, msgtype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, sysType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fromAppID_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, msgName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dms.MTransfCtrlOuterClass.MTransfCtrl)) {
        return super.equals(obj);
      }
      dms.MTransfCtrlOuterClass.MTransfCtrl other = (dms.MTransfCtrlOuterClass.MTransfCtrl) obj;

      boolean result = true;
      result = result && (hasMsgtype() == other.hasMsgtype());
      if (hasMsgtype()) {
        result = result && (getMsgtype()
            == other.getMsgtype());
      }
      result = result && (hasSysType() == other.hasSysType());
      if (hasSysType()) {
        result = result && (getSysType()
            == other.getSysType());
      }
      result = result && (hasTimestamp() == other.hasTimestamp());
      if (hasTimestamp()) {
        result = result && getTimestamp()
            .equals(other.getTimestamp());
      }
      result = result && (hasFromAppID() == other.hasFromAppID());
      if (hasFromAppID()) {
        result = result && getFromAppID()
            .equals(other.getFromAppID());
      }
      result = result && (hasMsgName() == other.hasMsgName());
      if (hasMsgName()) {
        result = result && getMsgName()
            .equals(other.getMsgName());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasMsgtype()) {
        hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getMsgtype();
      }
      if (hasSysType()) {
        hash = (37 * hash) + SYSTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSysType();
      }
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (hasFromAppID()) {
        hash = (37 * hash) + FROMAPPID_FIELD_NUMBER;
        hash = (53 * hash) + getFromAppID().hashCode();
      }
      if (hasMsgName()) {
        hash = (37 * hash) + MSGNAME_FIELD_NUMBER;
        hash = (53 * hash) + getMsgName().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dms.MTransfCtrlOuterClass.MTransfCtrl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dms.MTransfCtrlOuterClass.MTransfCtrl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dms.MTransfCtrl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dms.MTransfCtrl)
        dms.MTransfCtrlOuterClass.MTransfCtrlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dms.MTransfCtrlOuterClass.MTransfCtrl.class, dms.MTransfCtrlOuterClass.MTransfCtrl.Builder.class);
      }

      // Construct using dms.MTransfCtrlOuterClass.MTransfCtrl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgtype_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        sysType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fromAppID_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        msgName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dms.MTransfCtrlOuterClass.internal_static_dms_MTransfCtrl_descriptor;
      }

      public dms.MTransfCtrlOuterClass.MTransfCtrl getDefaultInstanceForType() {
        return dms.MTransfCtrlOuterClass.MTransfCtrl.getDefaultInstance();
      }

      public dms.MTransfCtrlOuterClass.MTransfCtrl build() {
        dms.MTransfCtrlOuterClass.MTransfCtrl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dms.MTransfCtrlOuterClass.MTransfCtrl buildPartial() {
        dms.MTransfCtrlOuterClass.MTransfCtrl result = new dms.MTransfCtrlOuterClass.MTransfCtrl(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgtype_ = msgtype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sysType_ = sysType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fromAppID_ = fromAppID_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.msgName_ = msgName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dms.MTransfCtrlOuterClass.MTransfCtrl) {
          return mergeFrom((dms.MTransfCtrlOuterClass.MTransfCtrl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dms.MTransfCtrlOuterClass.MTransfCtrl other) {
        if (other == dms.MTransfCtrlOuterClass.MTransfCtrl.getDefaultInstance()) return this;
        if (other.hasMsgtype()) {
          setMsgtype(other.getMsgtype());
        }
        if (other.hasSysType()) {
          setSysType(other.getSysType());
        }
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000004;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.hasFromAppID()) {
          bitField0_ |= 0x00000008;
          fromAppID_ = other.fromAppID_;
          onChanged();
        }
        if (other.hasMsgName()) {
          bitField0_ |= 0x00000010;
          msgName_ = other.msgName_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dms.MTransfCtrlOuterClass.MTransfCtrl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dms.MTransfCtrlOuterClass.MTransfCtrl) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgtype_ ;
      /**
       * <pre>
       *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
       * </pre>
       *
       * <code>optional int32 Msgtype = 1;</code>
       */
      public boolean hasMsgtype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
       * </pre>
       *
       * <code>optional int32 Msgtype = 1;</code>
       */
      public int getMsgtype() {
        return msgtype_;
      }
      /**
       * <pre>
       *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
       * </pre>
       *
       * <code>optional int32 Msgtype = 1;</code>
       */
      public Builder setMsgtype(int value) {
        bitField0_ |= 0x00000001;
        msgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *1 数据 | 2 请求| 3 回应 | 4 通知 ｜　5 程序状态监测
       * </pre>
       *
       * <code>optional int32 Msgtype = 1;</code>
       */
      public Builder clearMsgtype() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtype_ = 0;
        onChanged();
        return this;
      }

      private int sysType_ ;
      /**
       * <pre>
       *系统类型
       * </pre>
       *
       * <code>optional uint32 SysType = 2;</code>
       */
      public boolean hasSysType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *系统类型
       * </pre>
       *
       * <code>optional uint32 SysType = 2;</code>
       */
      public int getSysType() {
        return sysType_;
      }
      /**
       * <pre>
       *系统类型
       * </pre>
       *
       * <code>optional uint32 SysType = 2;</code>
       */
      public Builder setSysType(int value) {
        bitField0_ |= 0x00000002;
        sysType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *系统类型
       * </pre>
       *
       * <code>optional uint32 SysType = 2;</code>
       */
      public Builder clearSysType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sysType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object timestamp_ = "";
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *时间戳
       * </pre>
       *
       * <code>optional string Timestamp = 3;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fromAppID_ = "";
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       */
      public boolean hasFromAppID() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       */
      public java.lang.String getFromAppID() {
        java.lang.Object ref = fromAppID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fromAppID_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFromAppIDBytes() {
        java.lang.Object ref = fromAppID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fromAppID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       */
      public Builder setFromAppID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromAppID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       */
      public Builder clearFromAppID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fromAppID_ = getDefaultInstance().getFromAppID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息来源ID
       * </pre>
       *
       * <code>optional string FromAppID = 4;</code>
       */
      public Builder setFromAppIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fromAppID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object msgName_ = "";
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       */
      public boolean hasMsgName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       */
      public java.lang.String getMsgName() {
        java.lang.Object ref = msgName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            msgName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMsgNameBytes() {
        java.lang.Object ref = msgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       */
      public Builder setMsgName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       */
      public Builder clearMsgName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        msgName_ = getDefaultInstance().getMsgName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *传递的消息名称
       * </pre>
       *
       * <code>optional string MsgName = 5;</code>
       */
      public Builder setMsgNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        msgName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *传递的消息
       * </pre>
       *
       * <code>optional bytes data = 6;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *传递的消息
       * </pre>
       *
       * <code>optional bytes data = 6;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       *传递的消息
       * </pre>
       *
       * <code>optional bytes data = 6;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *传递的消息
       * </pre>
       *
       * <code>optional bytes data = 6;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dms.MTransfCtrl)
    }

    // @@protoc_insertion_point(class_scope:dms.MTransfCtrl)
    private static final dms.MTransfCtrlOuterClass.MTransfCtrl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dms.MTransfCtrlOuterClass.MTransfCtrl();
    }

    public static dms.MTransfCtrlOuterClass.MTransfCtrl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MTransfCtrl>
        PARSER = new com.google.protobuf.AbstractParser<MTransfCtrl>() {
      public MTransfCtrl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MTransfCtrl(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MTransfCtrl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MTransfCtrl> getParserForType() {
      return PARSER;
    }

    public dms.MTransfCtrlOuterClass.MTransfCtrl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dms_MTransfCtrl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dms_MTransfCtrl_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MTransfCtrl.proto\022\003dms\"t\n\013MTransfCtrl\022" +
      "\017\n\007Msgtype\030\001 \001(\005\022\017\n\007SysType\030\002 \001(\r\022\021\n\tTim" +
      "estamp\030\003 \001(\t\022\021\n\tFromAppID\030\004 \001(\t\022\017\n\007MsgNa" +
      "me\030\005 \001(\t\022\014\n\004data\030\006 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dms_MTransfCtrl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dms_MTransfCtrl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dms_MTransfCtrl_descriptor,
        new java.lang.String[] { "Msgtype", "SysType", "Timestamp", "FromAppID", "MsgName", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
